### PR TITLE
Fixed Health bug

### PR DESCRIPTION
**Pull request by aagoran**
health now updates live and displays properly
also added a subject2 class and overrides to meet the observer pattern style requirements

### CODE REVIEW

**Comment by aagoran** [comment]
refactored Mace to Mage else there were inconsistencies in the code

**Comment by aagoran** [comment]
added a Mage and working collisions to gameScreen1

**Comment by aagoran** [comment]
added code to differ height based on type of enemy

**Comment by aagoran** [comment]
added a ghost and a bat and respective collisions and health updates on GameScreen2

**Comment by aagoran** [comment]
added mage + knight on GameScreen3
health updates properly when there is a collision

**Review by Ashan-264 — APPROVED** [review]
Looks good

**Pull request merged**
